data st;
	WD="ASCORBIC ACID;BIOTIN;CALCIUM;CHROMIUM;COLECALCIFEROL;COPPER;FOLIC ACID;IODINE;MAGNESIUM;MALPIGHIA GLABRA FRUIT;MANGANESE;MOLYBDENUM;NICOTINAMIDE;PANTOTHENIC ACID;PYRIDOXINE HYDROCHLORIDE;RETINOL;RIBOFLAVIN;SELENIUM;VITAMIN B1 NOS;VITAMIN B12 NOS;VITAMIN E NOS;ZINC";
	_WD_=WD;
	length Sub $200 WD1 $200 WD2 $200 WD3 $200;
	array W{3} $ WD1-WD3;
	i=1;
	do while (_WD_^=""); 
		if (length(_WD_)<200) then do;
			W(i)=trim(_WD_);
			_WD_="";
		end;
		else do;
			sub=ksubstrb(_WD_,1,200);
			len=length(sub);
			lastloc=find(reverse(trim(sub)),";");
			W(i)=substr(_WD_,1,len-lastloc+1);
			_WD_=substr(_WD_,len-lastloc+2);
		end;
		i=i+1;
	end;
	drop Sub _WD_ WD3 len lastloc i;
run;
